---
title: Rychillie.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Rychillie
bio: "\U0001F44C\U0001F51D"
description: A blog about technology and game development
external-image: false
picture: assets/images/Rychillie.jpg
url: http://rychillie.net
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
analytics-google: UA-45575876-4
disqus: rychillie
facebook: rychillie
twitter: rychillie
instagram: rychillie
pinterest: rychillie
youtube: rychillie
github: rychillie
email: rychillie@hotmail.com
authors:
  rychillie:
    name: Rychillie
    bio: A little Geek
    external-image: false
    picture: assets/images/Rychillie.jpg
    twitter: rychillie
width: normal
projects: false
about: true
blog: true
read-time: true
show-tags: true
related: true
blog-nav-links: true
show-author: false
animation: true
sass:
  sass_dir: _sass
  style: :compressed
gems:
- jemoji
- jekyll-mentions
- jekyll-seo-tag
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-paginate
- jekyll-redirect-from
- jekyll-redirect-to
- jekyll-last-modified-at
jekyll-mentions:
  base_url: https://rychillie.net
